### ISSUE TITLE
"Download" and "Stay updated" sections look horrible

### ISSUE THREAD

**Issue by installgen2** [installgen2/tox.chat#8]
Additionally, we need to change the ID of the "Stay updated" section, as it is blocked by a lot of ad-blockers.

**Comment by lunarrunner** [comment]
I have some ideas about what could be done to make them look better.

In the *Download* section, I think the spacing between the links could be lowered as a first step. Looking at the current website, apart from the colour choices, that section seems better to me because it has one additional link in a row and the overall width of the table is shorter than the container in the new website.

As for the *Stay updated* section, how about merging it with the navigation bar? What I mean is that the navbar could have the following structure:

1. Wiki
2. Code
3. Stay updated (a dropdown menu)
    1. Follow us on Twitter
    2. Like us on Facebook
    3. Follow us on Twitter
4. Contact us (another dropdown menu)
    1. Mailing lists
    2. Join us on IRC

This way, having a separate *Stay updated* section is no longer necessary IMO.
Or, if you think that it's handy to have the social media icons unhidden, at the bottom of the page, then I would alternatively have them on the same level as the text about the licence, having them side by side and sharing the same background.

If you think it makes sense, I can make these changes and make a pull request. By the way, I'm looking for some experience in web development and I hope that this (and maybe other improvements, too) can be a good way to learn new things and help others at the same time.

**Comment by ProMcTagonist** [comment]
> if you think that it's handy to have the social media icons unhidden, at the bottom of the page,

+1

**Comment by installgen2** [comment]
Fixed
